project:
  type: website
  output-dir: docs

website:
  title: "Cole Rauscher"
  navbar:
    right:
      - href: projects.qmd
        text: Projects
      - href: index.qmd
        text: About
      - href: contactme.qmd
        text: Contact
  sidebar:
    title: "Projects"
    style: "docked"
    background: light
    contents:
      - projects.qmd
      - href: proj1.qmd
        text: "March Madness"

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: TRUE
    sidebar: TRUE



